# Generated by Django 2.2.5 on 2019-10-03 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shgroup', '0004_auto_20191002_1023'),
        ('survey', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('team', '0002_auto_20191002_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Project')),
                ('shGroup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shgroup.SHGroup')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('userPermission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Permission')),
            ],
        ),
    ]
