# Generated by Django 2.2.5 on 2019-10-03 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shgroup', '0004_auto_20191002_1023'),
        ('team', '0002_auto_20191002_0323'),
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('project_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectUsers',
            new_name='ProjectUser',
        ),
    ]
