# Generated by Django 2.2.5 on 2019-10-02 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
        ('shgroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapType', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=100)),
                ('SHCategoryName', models.CharField(max_length=50)),
                ('SHCategoryDesc', models.CharField(max_length=200)),
                ('shGroup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shgroup.SHGroup')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.Survey')),
            ],
        ),
    ]
