# Generated by Django 2.2.5 on 2019-10-02 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shgroup', '0002_shcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectUser', models.IntegerField()),
                ('relationshipStatus', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organization.Organization')),
                ('shCategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shgroup.SHCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
