# Generated by Django 2.2.5 on 2019-10-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amquestion',
            name='questionSequence',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='amresponse',
            name='integerValue',
            field=models.PositiveIntegerField(),
        ),
    ]
